<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'blog' => [[], ['_controller' => 'App\\Controller\\BlogController::index'], [], [['text', '/']], [], []],
    'figure_create' => [[], ['_controller' => 'App\\Controller\\BlogController::form'], [], [['text', '/blog/new']], [], []],
    'blog_edit' => [['id'], ['_controller' => 'App\\Controller\\BlogController::form'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/blog']], [], []],
    'blog_show' => [['id'], ['_controller' => 'App\\Controller\\BlogController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/blog']], [], []],
    'blog_delete' => [['id'], ['_controller' => 'App\\Controller\\BlogController::delete_figure'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/blog']], [], []],
    'figure_delete_image' => [['id'], ['_controller' => 'App\\Controller\\BlogController::deleteImage'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete/image']], [], []],
    'figure_delete_video' => [['id'], ['_controller' => 'App\\Controller\\BlogController::deleteVideo'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete/video']], [], []],
    'security_registration' => [[], ['_controller' => 'App\\Controller\\SecurityController::registration'], [], [['text', '/inscription']], [], []],
    'security_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/connexion']], [], []],
    'security_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/deconnexion']], [], []],
    'activation' => [['token'], ['_controller' => 'App\\Controller\\SecurityController::activation'], [], [['variable', '', '[^/]++', 'token', true], ['text', '/activation']], [], []],
    'app_forgotten_password' => [[], ['_controller' => 'App\\Controller\\SecurityController::forgottenPass'], [], [['text', '/oublipass']], [], []],
    'app_reset_password' => [['token'], ['_controller' => 'App\\Controller\\SecurityController::resetPassword'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/reset-pass']], [], []],
];
